//Login
export const LOGIN_FETCHING_DATA = 'LOGIN_FETCHING_DATA';
export const LOGIN_FETCHING_DATA_SUCCESS = 'LOGIN_FETCHING_DATA_SUCCESS';
export const LOGIN_FETCHING_DATA_ERROR = 'LOGIN_FETCHING_DATA_ERROR';

//Forget Password
export const FORGET_FETCHING_DATA = 'FORGET_FETCHING_DATA';
export const FORGET_FETCHING_DATA_SUCCESS = 'FORGET_FETCHING_DATA_SUCCESS';
export const FORGET_FETCHING_DATA_ERROR = 'FORGET_FETCHING_DATA_ERROR';


