export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECTION = 'SOCKET_CONNECTION';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_INITIAL_MESSAGES = 'SOCKET_INITIAL_MESSAGES';
export const SOCKET_READ_MESSAGES = 'SOCKET_READ_MESSAGES';
export const SOCKET_SUBSCRIBE = 'SOCKET_SUBSCRIBE';
export const SOCKET_UNSUBSCRIBE = 'SOCKET_UNSUBSCRIBE';

export const SOCKET_RECEIVE_MESSAGE = 'SOCKET_RECEIVE_MESSAGE';
export const SOCKET_RECEIVE_MESSAGE_ERROR = 'SOCKET_RECEIVE_MESSAGE_ERROR';
export const SOCKET_RECEIVE_MESSAGE_CLEAR = 'SOCKET_RECEIVE_MESSAGE_CLEAR';
export const SOCKET_UPDATE_CONVERSATIONS = 'SOCKET_UPDATE_CONVERSATIONS';
export const SOCKET_CONVERSATION_ERROR = 'SOCKET_CONVERSATION_ERROR';
export const SOCKET_SEND_MESSAGE = 'SOCKET_SEND_MESSAGE';
export const SOCKET_VIDEOCALL_PATIENT_CONNECTED =
  'SOCKET_VIDEOCALL_PATIENT_CONNECTED';
export const SOCKET_VIDEOCALL_PATIENT_DISCONNECTED = 'PATIENT_DISCONNECTED';
